name: 'GitHub Actions wakeup Bot'
 
on:
  push:
  schedule:
    - cron: '0 2 * * *'
 
jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v1
      - name: 'Get Wakeup'
        run: bash .github/workflows/wakeup.sh
      - name: 'Get Date'
        run: echo "REPORT_DATE=$(TZ=':Asia/Shanghai' date '+%Y-%m-%d %T')" >> $GITHUB_ENV
 
